### ISSUE TITLE
Could you add me real quick?

### ISSUE THREAD

**Issue by Hattorius** [h0nde/h0nde#1]
Hi Honda, I couldn't find your Discord anymore. Gotta talk to you: Hattorius#0563
I almost fixed the funcaptcha python thingy, but I got 1 more issue with decrypting images, maybe you can take a look at it?

**Comment by papycochon** [comment]
hackler moment

**Comment by fruityloops1** [comment]
haha i am very good at hacking i use kali loonix i am hacking the disc cord HAHHA owned "nigger" joinedf your server xdxd twitter.com/h0nde plEASe join my dead twitter accounwt thisis the bestmoment i am hacker only 11 years old please but me on great big story i am best hacker hahhre

**Comment by papycochon** [comment]
shut the fuck up
